server:
  port: ${SERVER_PORT}

spring:
  config:
    import: optional:file:src/main/resources/.env[.properties]
  application:
    name: jamkkaebi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST}
      port: ${SPRING_DATA_MONGODB_PORT}
      database: ${SPRING_DATA_MONGODB_DATABASE}
      username: ${SPRING_DATA_MONGODB_USERNAME}
      password: ${SPRING_DATA_MONGODB_PASSWORD}
      authentication-database: admin
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    show-sql: ${SPRING_JPA_SHOWSQL}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDLAUTO}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
        security: DEBUG
      hibernate:
        type:
          descriptor:
            sql: trace
    io:
      awspring:
        cloud: debug
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ss.SSSZ,Asia/Seoul

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    default-models-expand-depth: 2
    default-model-expand-depth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match: /api/v1/**

tmap:
  base-url: https://apis.openapi.sk.com/tmap
  app-key: ${TMAP_APPKEY}